In [4]:
import os, re
import json

from datetime import datetime
from utils import offset_calculate
import pandas as pd
import numpy as np

ROOT_DIR = os.path.join("C:/Users/wangz/OneDrive/University_RU/NSUWB/")
EPOCH_DT = datetime(1970,1,1)

In [5]:
df = pd.DataFrame({'B': [0, 1, 2, np.nan, 4]},
                  index = [pd.Timestamp('20130101 09:00:00'),
                           pd.Timestamp('20130101 09:00:02'),
                           pd.Timestamp('20130101 09:00:03'),
                           pd.Timestamp('20130101 09:00:05'),
                           pd.Timestamp('20130101 09:00:06')])

In [6]:
df

                       B
2013-01-01 09:00:00  0.0
2013-01-01 09:00:02  1.0
2013-01-01 09:00:03  2.0
2013-01-01 09:00:05  NaN
2013-01-01 09:00:06  4.0

In [8]:
df.rolling('1s').sum()

                       B
2013-01-01 09:00:00  0.0
2013-01-01 09:00:02  1.0
2013-01-01 09:00:03  2.0
2013-01-01 09:00:05  NaN
2013-01-01 09:00:06  4.0

In [23]:
n = 51
index = pd.date_range('2019-01-01 00:00:00', periods=n, freq='S')
y = np.sin(np.linspace(0, 10, n)) + np.random.rand(n)

dt = pd.DataFrame({'value': y}, index=index)
dt = dt.resample('0.0001S').mean()
print(dt.head())

                        value
2019-01-01 00:00:00  0.579297
2019-01-01 00:00:01  0.600690
2019-01-01 00:00:02  0.491894
2019-01-01 00:00:03  0.966011
2019-01-01 00:00:04  1.473682
2019-01-01 00:00:05  1.217325
2019-01-01 00:00:06  1.520367
2019-01-01 00:00:07  1.296065
2019-01-01 00:00:08  1.693944
2019-01-01 00:00:09  1.525172
2019-01-01 00:00:10  1.402453
2019-01-01 00:00:11  1.004778
2019-01-01 00:00:12  1.024889
2019-01-01 00:00:13  0.821504
2019-01-01 00:00:14  0.980990
2019-01-01 00:00:15  0.691016
2019-01-01 00:00:16  0.056092
2019-01-01 00:00:17  0.604587
2019-01-01 00:00:18  0.094719
2019-01-01 00:00:19 -0.159285
2019-01-01 00:00:20 -0.371038
2019-01-01 00:00:21 -0.778099
2019-01-01 00:00:22 -0.102747
2019-01-01 00:00:23 -0.590189
2019-01-01 00:00:24 -0.068277
2019-01-01 00:00:25 -0.512059
2019-01-01 00:00:26 -0.830624
2019-01-01 00:00:27 -0.352700
2019-01-01 00:00:28 -0.097782
2019-01-01 00:00:29 -0.382757
2019-01-01 00:00:30  0.168063
2019-01-01 00:00:31 -0.072813
2019-01-01 00:00:32  0.492431
2019-01-01 00:00:33  1.277652
2019-01-01 00:00:34  0.494203
2019-01-01 00:00:35  0.731505
2019-01-01 00:00:36  1.427305
2019-01-01 00:00:37  1.472326
2019-01-01 00:00:38  1.723110
2019-01-01 00:00:39  1.635860
2019-01-01 00:00:40  1.250292
2019-01-01 00:00:41  1.212639
2019-01-01 00:00:42  1.347631
2019-01-01 00:00:43  0.918604
2019-01-01 00:00:44  1.020571
2019-01-01 00:00:45  1.147303
2019-01-01 00:00:46  1.150339
2019-01-01 00:00:47  0.895274
2019-01-01 00:00:48  0.376602
2019-01-01 00:00:49  0.596909
2019-01-01 00:00:50 -0.054387

In [12]:
index

DatetimeIndex(['2019-01-01 00:00:00', '2019-01-01 00:00:01',
               '2019-01-01 00:00:02', '2019-01-01 00:00:03',
               '2019-01-01 00:00:04', '2019-01-01 00:00:05',
               '2019-01-01 00:00:06', '2019-01-01 00:00:07',
               '2019-01-01 00:00:08', '2019-01-01 00:00:09',
               '2019-01-01 00:00:10', '2019-01-01 00:00:11',
               '2019-01-01 00:00:12', '2019-01-01 00:00:13',
               '2019-01-01 00:00:14', '2019-01-01 00:00:15',
               '2019-01-01 00:00:16', '2019-01-01 00:00:17',
               '2019-01-01 00:00:18', '2019-01-01 00:00:19',
               '2019-01-01 00:00:20', '2019-01-01 00:00:21',
               '2019-01-01 00:00:22', '2019-01-01 00:00:23',
               '2019-01-01 00:00:24', '2019-01-01 00:00:25',
               '2019-01-01 00:00:26', '2019-01-01 00:00:27',
               '2019-01-01 00:00:28', '2019-01-01 00:00:29',
               '2019-01-01 00:00:30', '2019-01-01 00:00:31',
               '2019-01-01 00:00:32', '2019-01-01 00:00:33',
               '2019-01-01 00:00:34', '2019-01-01 00:00:35',
               '2019-01-01 00:00:36', '2019-01-01 00:00:37',
               '2019-01-01 00:00:38', '2019-01-01 00:00:39',
               '2019-01-01 00:00:40', '2019-01-01 00:00:41',
               '2019-01-01 00:00:42', '2019-01-01 00:00:43',
               '2019-01-01 00:00:44', '2019-01-01 00:00:45',
               '2019-01-01 00:00:46', '2019-01-01 00:00:47',
               '2019-01-01 00:00:48', '2019-01-01 00:00:49',
               '2019-01-01 00:00:50'],
              dtype='datetime64[ns]', freq='S')